# Generated by Django 4.2 on 2025-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, upload_to='blog_images', verbose_name='Blog Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(max_length=264, verbose_name='Title'),
        ),
    ]
