# Generated by Django 4.2 on 2025-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-user.png', upload_to='profile_pics'),
        ),
    ]
