# Generated by Django 4.2 on 2025-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0002_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-img.jpg', upload_to='profile_pics'),
        ),
    ]
